version: "3"

services:
  chrome:
          image: selenium/standalone-chrome:4.15.0-20231129
          restart: "no"
          shm_size: 2gb
          ports:
            - 4444:4444
            - 7900:7900

  app:
          build: .
          restart: "no"
          ports:
            - 8000:8000
          depends_on:
            - chrome
          volumes:
            - ./outputs:/outputs